#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("XamarinXO.Droid.Resource", IsApplication=true)]

namespace XamarinXO.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050000
			public const int bt1 = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int bt2 = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int bt3 = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int bt4 = 2131034115;
			
			// aapt resource value: 0x7f050004
			public const int bt5 = 2131034116;
			
			// aapt resource value: 0x7f050005
			public const int bt6 = 2131034117;
			
			// aapt resource value: 0x7f050006
			public const int bt7 = 2131034118;
			
			// aapt resource value: 0x7f050007
			public const int bt8 = 2131034119;
			
			// aapt resource value: 0x7f050008
			public const int bt9 = 2131034120;
			
			// aapt resource value: 0x7f050010
			public const int btnForget = 2131034128;
			
			// aapt resource value: 0x7f050013
			public const int btnInvite = 2131034131;
			
			// aapt resource value: 0x7f05000d
			public const int btnLogin = 2131034125;
			
			// aapt resource value: 0x7f05000f
			public const int btnLogout = 2131034127;
			
			// aapt resource value: 0x7f050012
			public const int btnRefresh = 2131034130;
			
			// aapt resource value: 0x7f05000e
			public const int btnReg = 2131034126;
			
			// aapt resource value: 0x7f050011
			public const int etClients = 2131034129;
			
			// aapt resource value: 0x7f05000c
			public const int etEmail = 2131034124;
			
			// aapt resource value: 0x7f05000a
			public const int etLogin = 2131034122;
			
			// aapt resource value: 0x7f05000b
			public const int etPassword = 2131034123;
			
			// aapt resource value: 0x7f050014
			public const int tvName = 2131034132;
			
			// aapt resource value: 0x7f050009
			public const int tvStatus = 2131034121;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int app_name = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
